#!/usr/bin/perl -w
open (FILE1,$ARGV[0]);
@lines = <FILE1>;
close FILE1;
open (FILE2, $ARGV[1]);
$i = 0;
while (($line = <FILE2> ) || (defined $lines[$i])){
    if (defined $lines[$i]){
        print STDOUT $lines[$i];
        $i++;
    }
    if (defined $line){
        print STDOUT $line;
    }
}

