#!/usr/bin/perl -w
die "Not enough arguments\n" if @ARGV < 1;
$regexp = shift @ARGV;
foreach $arg (@ARGV){
    @strings = `/usr/bin/strings $arg`;
    foreach $string (@strings){
        if ($string =~ qr/$regexp/){
            print "$arg:$string";
        }
    }
}
