#!/usr/bin/perl -w
die "Usage: perl2 regexp file1 file2.." unless @ARGV >= 2;

$regexp = shift @ARGV;

foreach $arg (@ARGV){
    open (FILE,$arg);
    @check = <FILE>;
    close FILE;
    @match = grep(/$regexp/,@check);
    foreach $mtch (@match){
        print "$arg:$mtch";
    }
} 
