#!/usr/bin/perl -w
die "Usage: sperl8 fileExt1 fileExt2 dir" unless @ARGV == 3;
$file1 = $ARGV[0];
$file2 = $ARGV[1];
$dir = $ARGV[2];

@find = `/usr/bin/find $dir -type f -name "*.$file1"`;

@find = sort @find;

@mv = @find;

chop @find;

grep(s/.$file1\s+/.$file2/g,@mv);

for ($i = 0; $i < @find; $i++){
    print "mv $find[$i] $mv[$i]\n";
}
